name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v2.3.1
      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x' # Keep Node.js 14 as required
      - name: Install dependencies with npm ci
        run: npm ci
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34
      - name: Install the gh-pages CLI
        run: npm install -g gh-pages
      - name: Build and deploy
        env:
          TOKEN: ${{ secrets.DAVES_DEPLOY }}
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/RLeapFROGS.git
